### ISSUE TITLE
How do you detect a box

### ISSUE THREAD

**Issue by Bl00d-B0b** [Ednaz/e2binary#2]
Hello,

new version is available of enigma2. after update, i try to update your package with force. and seems box is not detected. how do you detect a bix? i change hostname.

Ed

**Comment by Ednaz** [comment]
`uname -n`

**Comment by Bl00d-B0b** [comment]
I see,
Now I understand, why your script fails. 
I have several 4K boxes at my house, and I change hostname. 
maybe you can implement other method to detect enigma2 hardware??

Ed
