### ISSUE TITLE
binary for OpenPLI-7.2.rc ?

### ISSUE THREAD

**Issue by shhaldon** [Ednaz/e2binary#3]
hi,

is there a plan to make a e2 binary for openpli-7.2.rc

regards

**Comment by Ednaz** [comment]
Hi
Not yet in the plans. This is a temporary test version, it will soon be without support. I see no reason to spend a lot of time compiling.
If you really need to, write the model of your receiver, if there is time, I will collect it.

**Comment by shhaldon** [comment]
Hi Ednaz,

> If you really need to, write the model of your receiver, if there is time, I will collect it.

thanks a lot,
my box is a VU Ultimo 4k

regards
ahhaldon

**Comment by shhaldon** [comment]
Hi Ednaz,

If you really need to, write the model of your receiver, if there is time,
> I will collect it.
>
thanks a lot
my receiver is a VU Ultimo 4k

regards
shhaldon

Am Do., 10. Okt. 2019 um 22:01 Uhr schrieb Ednaz <notifications@github.com>:

**Comment by Ednaz** [comment]
@shhaldon 
Try installing the binary manually
How to do this is described in README.md

**Comment by shhaldon** [comment]
Hi Ednaz,

many thanks  - it works perfect ☺

regards
shhaldon

Am So., 13. Okt. 2019 um 13:19 Uhr schrieb Ednaz <notifications@github.com>:
