### ISSUE TITLE
Tricolor TV HD & 4K channels

### ISSUE THREAD

**Issue by Bl00d-B0b** [Ednaz/e2binary#4]
Hello,

Tricolor HD & 4K channels stop to work. but worked before.  with last release

Ed

**Comment by Ednaz** [comment]
What version of the image are you using?

**Comment by Bl00d-B0b** [comment]
hello,

I use openpli 7.1-release last update with your last version. everything works 1,5 months ago. only 2 channels not worked. but now mostly all HD and 4K not working.

**Comment by Ednaz** [comment]
Hello
what receivers?

**Comment by Bl00d-B0b** [comment]
Vu 4k ultima

2019-11-03, sk 14:44, Ednaz <notifications@github.com> rašė:

**Comment by Ednaz** [comment]
All binaries updated for OpenPli 7.1 release

**Comment by Bl00d-B0b** [comment]
Does not help. just updated. I can send you mpg stream, to see how it's works. seems tricolor make some protection.

**Comment by Ednaz** [comment]
Если Вы смотрите Триколор, значит понимаете русский язык. Я правильно понимаю?
Пишите тогда на русском языке.
Покажите мне поток как пишет. Посмотрите в настройках модуля Задержка, если иитам установлено 256, то установите 64 и проверьте. Жалоб от пользователей ресивером Ultimo4k нет, значит проблема у Вас локальная.

**Comment by Bl00d-B0b** [comment]
Dobryj Den.

Ja seichas v Kazahstane, tut internet nedosatochno shtoby pereslat vam
potok. no vigliadit eto tak, seryj ekran, proskakivajut kakijeto kubiki i
zvuk idiot s klikanijem.
[image: image.png]
A v kakom meniu mne posmotret eti ustanovki

**Comment by Bl00d-B0b** [comment]
Hello,

Pomenial dvb ci delay s 256 na 64, i poshlo.
Spasibo za pomosch

Ed

**Comment by Ednaz** [comment]
Не за что.
