### ISSUE TITLE
enigma2 can't stream in stendby

### ISSUE THREAD

**Issue by Bl00d-B0b** [Ednaz/e2binary#6]
Hello,

last release of enigma2 fixed LNB driver. it was an bug, can't stream or save in standby mode.

This release now fix this bug:
OpenPLi 7.2-release (2020-03-09-release-7.2)
Kernel / Drivers: | 3.14.28 / 3.14.28-20190424.r0.1

OpenPli support:
"but I recall issues around LNB power in standby, which were fixed in the latest driver update."

is it possible to have a new recompile, at least for VU+

Ed

**Comment by Ednaz** [comment]
new compile 20200413
